version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seeker_provider_db
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
