"""modify services_offer type to JSON type

Revision ID: 06c77837622d
Revises: 3925eaa1acaf
Create Date: 2025-02-26 16:57:08.537747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06c77837622d'
down_revision = '3925eaa1acaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('services_offered',
               existing_type=sa.VARCHAR(length=1024),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('services_offered',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###
